// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homeHandle = ffai.ProjectPageHandle<HomeParams, HomeState>(
  name: "Home",
  key: "Scaffold_7jj2za04",
  route: "home",
  params: const HomeParams(),
  state: const HomeState(),
  widgets: HomeWidgets.tree,
);

final class HomeParams {
  const HomeParams();
}

final class HomeState {
  const HomeState();
}

abstract final class HomeWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7jj2za04",
      type: "Scaffold",
      path: "Home",
      name: "Home",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_z10y3sxp",
            type: "AppBar",
            path: "Home.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_ii8kh2uu",
                  type: "Text",
                  path: "Home.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "หน้าหลัก",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_8n20shdw",
            type: "Container",
            path: "Home.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_m1lfffg2",
                type: "Column",
                path: "Home.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_huzvqefh",
                    type: "Text",
                    path: "Home.body[0].children[0].children[0]",
                    name: "WelcomeText",
                    text: "ยินดีต้อนรับ",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_iw48u0hm",
                    type: "Button",
                    path: "Home.body[0].children[0].children[1]",
                    name: "LogoutButton",
                    text: "ออกจากระบบ",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

