// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final homeAdminHandle = ffai.ProjectPageHandle<HomeAdminParams, HomeAdminState>(
  name: "HomeAdmin",
  key: "Scaffold_sllg2xzc",
  route: "home-admin",
  params: const HomeAdminParams(),
  state: const HomeAdminState(),
  widgets: HomeAdminWidgets.tree,
);

final class HomeAdminParams {
  const HomeAdminParams();
}

final class HomeAdminState {
  const HomeAdminState();
}

abstract final class HomeAdminWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_sllg2xzc",
      type: "Scaffold",
      path: "HomeAdmin",
      name: "HomeAdmin",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_7oucwhy4",
            type: "AppBar",
            path: "HomeAdmin.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_8ji7j3ba",
                  type: "Text",
                  path: "HomeAdmin.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "หน้าแอดมิน",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_letqtu6s",
            type: "Container",
            path: "HomeAdmin.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_v1t33hpl",
                type: "Column",
                path: "HomeAdmin.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_0sua5o7s",
                    type: "Text",
                    path: "HomeAdmin.body[0].children[0].children[0]",
                    name: "WelcomeAdminText",
                    text: "โซนผู้ดูแลระบบ",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_yd4f7vhl",
                    type: "Button",
                    path: "HomeAdmin.body[0].children[0].children[1]",
                    name: "LogoutAdminButton",
                    text: "ออกจากระบบ",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

