// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final loginHandle = ffai.ProjectPageHandle<LoginParams, LoginState>(
  name: "Login",
  key: "Scaffold_sl7hmuyx",
  route: "login",
  params: const LoginParams(),
  state: const LoginState(),
  widgets: LoginWidgets.tree,
);

final class LoginParams {
  const LoginParams();
}

final class LoginState {
  const LoginState();
  ffai.ProjectStateFieldHandle get loginEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "loginEmail",
        key: "3phzmonl",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get loginPassword =>
      const ffai.ProjectStateFieldHandle(
        name: "loginPassword",
        key: "hzsp3wr0",
        typeName: "String",
      );
}

abstract final class LoginWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_sl7hmuyx",
      type: "Scaffold",
      path: "Login",
      name: "Login",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_b8wcs0aa",
            type: "AppBar",
            path: "Login.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_vnhjafcd",
                  type: "Text",
                  path: "Login.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "เข้าสู่ระบบ",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_f9lol9z5",
            type: "Container",
            path: "Login.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_m06ntd9w",
                type: "Column",
                path: "Login.body[0].children[0]",
                name: "LoginForm",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "TextField_ydjp08lq",
                    type: "TextField",
                    path: "Login.body[0].children[0].children[0]",
                    name: "LoginEmailField",
                    text: "อีเมล",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_2r888r8k",
                    type: "TextField",
                    path: "Login.body[0].children[0].children[1]",
                    name: "LoginPasswordField",
                    text: "รหัสผ่าน",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_uf2o38oc",
                    type: "Button",
                    path: "Login.body[0].children[0].children[2]",
                    name: "LoginButton",
                    text: "เข้าสู่ระบบ",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_7o9yclm5",
                    type: "Button",
                    path: "Login.body[0].children[0].children[3]",
                    name: "GoToSignUpButton",
                    text: "ยังไม่มีบัญชี? สมัครสมาชิก",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

