// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final signUpHandle = ffai.ProjectPageHandle<SignUpParams, SignUpState>(
  name: "SignUp",
  key: "Scaffold_qxe5iu54",
  route: "sign-up",
  params: const SignUpParams(),
  state: const SignUpState(),
  widgets: SignUpWidgets.tree,
);

final class SignUpParams {
  const SignUpParams();
}

final class SignUpState {
  const SignUpState();
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "2c70za1f",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get fullName =>
      const ffai.ProjectStateFieldHandle(
        name: "fullName",
        key: "4fw5nxyl",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "8hsx3nem",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get phone =>
      const ffai.ProjectStateFieldHandle(
        name: "phone",
        key: "k8ms6vp3",
        typeName: "String",
      );
}

abstract final class SignUpWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_qxe5iu54",
      type: "Scaffold",
      path: "SignUp",
      name: "SignUp",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_gcwzeird",
            type: "AppBar",
            path: "SignUp.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_0imcxx7a",
                  type: "Text",
                  path: "SignUp.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "สมัครสมาชิก",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_3i4zm612",
            type: "Container",
            path: "SignUp.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_tnrrwj9h",
                type: "Column",
                path: "SignUp.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "TextField_d8t8nj3h",
                    type: "TextField",
                    path: "SignUp.body[0].children[0].children[0]",
                    name: "FullNameField",
                    text: "ชื่อ-นามสกุล",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_2vf9e69r",
                    type: "TextField",
                    path: "SignUp.body[0].children[0].children[1]",
                    name: "EmailField",
                    text: "อีเมล",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_h8y1iyyv",
                    type: "TextField",
                    path: "SignUp.body[0].children[0].children[2]",
                    name: "PhoneField",
                    text: "เบอร์โทร (ไม่บังคับ)",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_ajuzm8t0",
                    type: "TextField",
                    path: "SignUp.body[0].children[0].children[3]",
                    name: "PasswordField",
                    text: "รหัสผ่าน",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_9artafpq",
                    type: "Button",
                    path: "SignUp.body[0].children[0].children[4]",
                    name: "SignUpButton",
                    text: "สมัครสมาชิก",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

