// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const email = ffai.ProjectAppStateFieldHandle(
    name: "email",
    key: "51e2rvim",
    typeName: "String",
    persisted: false,
  );
  static const fullName = ffai.ProjectAppStateFieldHandle(
    name: "fullName",
    key: "de5jg5r0",
    typeName: "String",
    persisted: false,
  );
  static const password = ffai.ProjectAppStateFieldHandle(
    name: "password",
    key: "4awa303y",
    typeName: "String",
    persisted: false,
  );
  static const phone = ffai.ProjectAppStateFieldHandle(
    name: "phone",
    key: "aoxsi7h3",
    typeName: "String",
    persisted: false,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[
    email,
    fullName,
    password,
    phone,
  ];
}

