// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/home.dart' show homeHandle;
import 'pages/home_admin.dart' show homeAdminHandle;
import 'pages/login.dart' show loginHandle;
import 'pages/sign_up.dart' show signUpHandle;

abstract final class Pages {
  static final home = homeHandle;
  static final homeAdmin = homeAdminHandle;
  static final login = loginHandle;
  static final signUp = signUpHandle;
  static final all = <ffai.ProjectPageHandle>[
    home,
    homeAdmin,
    login,
    signUp,
  ];
}
