// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class Project {
  static const id = "m-j-u-market-v2-0xhjhg";
  static const name = "MJU-Market-v2";
  static const sdkMetaVersion = 2;
}
