// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'dart:collection';

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static const all = <ffai.StructHandle>[];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static final cat = ffai.ProjectTableHandle<CatFields>(
    name: "CAT",
    description: "",
    isView: false,
    fields: CatFields(),
  );
  static final profile = ffai.ProjectTableHandle<ProfileFields>(
    name: "Profile",
    description: "",
    isView: false,
    fields: ProfileFields(),
  );
  static final chat = ffai.ProjectTableHandle<ChatFields>(
    name: "chat",
    description: "",
    isView: false,
    fields: ChatFields(),
  );
  static final chatMessage = ffai.ProjectTableHandle<ChatMessageFields>(
    name: "chat_message",
    description: "",
    isView: false,
    fields: ChatMessageFields(),
  );
  static final chatMessagesView = ffai.ProjectTableHandle<ChatMessagesViewFields>(
    name: "chat_messages_view",
    description: "",
    isView: true,
    fields: ChatMessagesViewFields(),
  );
  static final chatSummary = ffai.ProjectTableHandle<ChatSummaryFields>(
    name: "chat_summary",
    description: "",
    isView: true,
    fields: ChatSummaryFields(),
  );
  static final chatUser = ffai.ProjectTableHandle<ChatUserFields>(
    name: "chat_user",
    description: "",
    isView: false,
    fields: ChatUserFields(),
  );
  static final products = ffai.ProjectTableHandle<ProductsFields>(
    name: "products",
    description: "",
    isView: false,
    fields: ProductsFields(),
  );
  static final productsReviewView = ffai.ProjectTableHandle<ProductsReviewViewFields>(
    name: "products_review_view",
    description: "",
    isView: true,
    fields: ProductsReviewViewFields(),
  );
  static final publicProfiles = ffai.ProjectTableHandle<PublicProfilesFields>(
    name: "public_profiles",
    description: "",
    isView: true,
    fields: PublicProfilesFields(),
  );
  static final reports = ffai.ProjectTableHandle<ReportsFields>(
    name: "reports",
    description: "",
    isView: false,
    fields: ReportsFields(),
  );
  static final all = <ffai.ProjectTableHandle>[
    cat,
    profile,
    chat,
    chatMessage,
    chatMessagesView,
    chatSummary,
    chatUser,
    products,
    productsReviewView,
    publicProfiles,
    reports,
  ];
}

final class CatFields extends MapBase<String, ffai.PostgresTableField> {
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final name = ffai.ProjectTableFieldHandle(
    name: "name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "id",
    "name",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "id" => id,
    "name" => name,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ProfileFields extends MapBase<String, ffai.PostgresTableField> {
  final avatarUrl = ffai.ProjectTableFieldHandle(
    name: "avatar_url",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final bio = ffai.ProjectTableFieldHandle(
    name: "bio",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final email = ffai.ProjectTableFieldHandle(
    name: "email",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final fullName = ffai.ProjectTableFieldHandle(
    name: "full_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "users.id",
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final phone = ffai.ProjectTableFieldHandle(
    name: "phone",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final role = ffai.ProjectTableFieldHandle(
    name: "role",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final studentId = ffai.ProjectTableFieldHandle(
    name: "student_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "avatar_url",
    "bio",
    "created_at",
    "email",
    "full_name",
    "id",
    "phone",
    "role",
    "student_id",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "avatar_url" => avatarUrl,
    "bio" => bio,
    "created_at" => createdAt,
    "email" => email,
    "full_name" => fullName,
    "id" => id,
    "phone" => phone,
    "role" => role,
    "student_id" => studentId,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ChatFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final lastMessage = ffai.ProjectTableFieldHandle(
    name: "last_message",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "id",
    "last_message",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "id" => id,
    "last_message" => lastMessage,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ChatMessageFields extends MapBase<String, ffai.PostgresTableField> {
  final chatId = ffai.ProjectTableFieldHandle(
    name: "chat_id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: "chat.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final message = ffai.ProjectTableFieldHandle(
    name: "message",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final userId = ffai.ProjectTableFieldHandle(
    name: "user_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "Profile.id",
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "chat_id",
    "created_at",
    "id",
    "message",
    "user_id",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "chat_id" => chatId,
    "created_at" => createdAt,
    "id" => id,
    "message" => message,
    "user_id" => userId,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ChatMessagesViewFields extends MapBase<String, ffai.PostgresTableField> {
  final chatId = ffai.ProjectTableFieldHandle(
    name: "chat_id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final message = ffai.ProjectTableFieldHandle(
    name: "message",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final messageId = ffai.ProjectTableFieldHandle(
    name: "message_id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final senderName = ffai.ProjectTableFieldHandle(
    name: "sender_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final userId = ffai.ProjectTableFieldHandle(
    name: "user_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "chat_id",
    "created_at",
    "message",
    "message_id",
    "sender_name",
    "user_id",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "chat_id" => chatId,
    "created_at" => createdAt,
    "message" => message,
    "message_id" => messageId,
    "sender_name" => senderName,
    "user_id" => userId,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ChatSummaryFields extends MapBase<String, ffai.PostgresTableField> {
  final chatId = ffai.ProjectTableFieldHandle(
    name: "chat_id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final lastMessage = ffai.ProjectTableFieldHandle(
    name: "last_message",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final memberNames = ffai.ProjectTableFieldHandle(
    name: "member_names",
    key: "",
    typeName: "List<String>",
    type: ffai.listOf(ffai.string),
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final userIds = ffai.ProjectTableFieldHandle(
    name: "user_ids",
    key: "",
    typeName: "List<String>",
    type: ffai.listOf(ffai.string),
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "chat_id",
    "created_at",
    "last_message",
    "member_names",
    "user_ids",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "chat_id" => chatId,
    "created_at" => createdAt,
    "last_message" => lastMessage,
    "member_names" => memberNames,
    "user_ids" => userIds,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ChatUserFields extends MapBase<String, ffai.PostgresTableField> {
  final chatId = ffai.ProjectTableFieldHandle(
    name: "chat_id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: "chat.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: true,
    hasDefault: false,
  );
  final userId = ffai.ProjectTableFieldHandle(
    name: "user_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "Profile.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "chat_id",
    "created_at",
    "id",
    "user_id",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "chat_id" => chatId,
    "created_at" => createdAt,
    "id" => id,
    "user_id" => userId,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ProductsFields extends MapBase<String, ffai.PostgresTableField> {
  final categoryId = ffai.ProjectTableFieldHandle(
    name: "category_id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: "CAT.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final condition = ffai.ProjectTableFieldHandle(
    name: "condition",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final contactPhone = ffai.ProjectTableFieldHandle(
    name: "contact_phone",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final description = ffai.ProjectTableFieldHandle(
    name: "description",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final imageUrls = ffai.ProjectTableFieldHandle(
    name: "image_urls",
    key: "",
    typeName: "List<String>",
    type: ffai.listOf(ffai.string),
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final moderationStatus = ffai.ProjectTableFieldHandle(
    name: "moderation_status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final price = ffai.ProjectTableFieldHandle(
    name: "price",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final rejectionReason = ffai.ProjectTableFieldHandle(
    name: "rejection_reason",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final sellerId = ffai.ProjectTableFieldHandle(
    name: "seller_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "Profile.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final status = ffai.ProjectTableFieldHandle(
    name: "status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final title = ffai.ProjectTableFieldHandle(
    name: "title",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "category_id",
    "condition",
    "contact_phone",
    "created_at",
    "description",
    "id",
    "image_urls",
    "moderation_status",
    "price",
    "rejection_reason",
    "seller_id",
    "status",
    "title",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "category_id" => categoryId,
    "condition" => condition,
    "contact_phone" => contactPhone,
    "created_at" => createdAt,
    "description" => description,
    "id" => id,
    "image_urls" => imageUrls,
    "moderation_status" => moderationStatus,
    "price" => price,
    "rejection_reason" => rejectionReason,
    "seller_id" => sellerId,
    "status" => status,
    "title" => title,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ProductsReviewViewFields extends MapBase<String, ffai.PostgresTableField> {
  final categoryId = ffai.ProjectTableFieldHandle(
    name: "category_id",
    key: "",
    typeName: "Integer",
    type: ffai.int_,
    description: "",
    postgresType: "int8",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final categoryName = ffai.ProjectTableFieldHandle(
    name: "category_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final condition = ffai.ProjectTableFieldHandle(
    name: "condition",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final contactPhone = ffai.ProjectTableFieldHandle(
    name: "contact_phone",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final description = ffai.ProjectTableFieldHandle(
    name: "description",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final imageUrls = ffai.ProjectTableFieldHandle(
    name: "image_urls",
    key: "",
    typeName: "List<String>",
    type: ffai.listOf(ffai.string),
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final moderationStatus = ffai.ProjectTableFieldHandle(
    name: "moderation_status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final price = ffai.ProjectTableFieldHandle(
    name: "price",
    key: "",
    typeName: "Double",
    type: ffai.double_,
    description: "",
    postgresType: "numeric",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final rejectionReason = ffai.ProjectTableFieldHandle(
    name: "rejection_reason",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final sellerId = ffai.ProjectTableFieldHandle(
    name: "seller_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final sellerName = ffai.ProjectTableFieldHandle(
    name: "seller_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final status = ffai.ProjectTableFieldHandle(
    name: "status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final title = ffai.ProjectTableFieldHandle(
    name: "title",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "category_id",
    "category_name",
    "condition",
    "contact_phone",
    "created_at",
    "description",
    "id",
    "image_urls",
    "moderation_status",
    "price",
    "rejection_reason",
    "seller_id",
    "seller_name",
    "status",
    "title",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "category_id" => categoryId,
    "category_name" => categoryName,
    "condition" => condition,
    "contact_phone" => contactPhone,
    "created_at" => createdAt,
    "description" => description,
    "id" => id,
    "image_urls" => imageUrls,
    "moderation_status" => moderationStatus,
    "price" => price,
    "rejection_reason" => rejectionReason,
    "seller_id" => sellerId,
    "seller_name" => sellerName,
    "status" => status,
    "title" => title,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class PublicProfilesFields extends MapBase<String, ffai.PostgresTableField> {
  final avatarUrl = ffai.ProjectTableFieldHandle(
    name: "avatar_url",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final fullName = ffai.ProjectTableFieldHandle(
    name: "full_name",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "avatar_url",
    "full_name",
    "id",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "avatar_url" => avatarUrl,
    "full_name" => fullName,
    "id" => id,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

final class ReportsFields extends MapBase<String, ffai.PostgresTableField> {
  final createdAt = ffai.ProjectTableFieldHandle(
    name: "created_at",
    key: "",
    typeName: "DateTime",
    type: ffai.dateTime,
    description: "",
    postgresType: "timestamptz",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: true,
  );
  final id = ffai.ProjectTableFieldHandle(
    name: "id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: null,
    isPrimaryKey: true,
    isRequired: false,
    hasDefault: true,
  );
  final reason = ffai.ProjectTableFieldHandle(
    name: "reason",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "text",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final reportedProductId = ffai.ProjectTableFieldHandle(
    name: "reported_product_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "products.id",
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );
  final reporterId = ffai.ProjectTableFieldHandle(
    name: "reporter_id",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "uuid",
    foreignKey: "Profile.id",
    isPrimaryKey: false,
    isRequired: true,
    hasDefault: false,
  );
  final status = ffai.ProjectTableFieldHandle(
    name: "status",
    key: "",
    typeName: "String",
    type: ffai.string,
    description: "",
    postgresType: "varchar",
    foreignKey: null,
    isPrimaryKey: false,
    isRequired: false,
    hasDefault: false,
  );

  @override
  Iterable<String> get keys => const <String>[
    "created_at",
    "id",
    "reason",
    "reported_product_id",
    "reporter_id",
    "status",
  ];

  @override
  ffai.PostgresTableField? operator [](Object? key) => switch (key) {
    "created_at" => createdAt,
    "id" => id,
    "reason" => reason,
    "reported_product_id" => reportedProductId,
    "reporter_id" => reporterId,
    "status" => status,
    _ => null,
  };

  @override
  void operator []=(String key, ffai.PostgresTableField value) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  void clear() => throw UnsupportedError('Generated project SDK fields are read-only.');

  @override
  ffai.PostgresTableField? remove(Object? key) =>
      throw UnsupportedError('Generated project SDK fields are read-only.');
}

abstract final class CustomCode {
  static const functions = <String>[
  ];
  static const actions = <String>[
    "IsCurrentUserAdmin",
    "SignUpWithProfile",
  ];
  static const widgets = <String>[
  ];
}

